description: Restores and saves the tools node_modules directory
steps:
  - restore_cache:
      name: Restore Yarn Tools Package Cache
      key: 2-yarn-{{ arch }}-{{ checksum "tools/yarn.lock" }}-{{ checksum "tools/package.json" }}
  - run:
      name: Install Dependencies
      command: yarn install --immutable
      working_directory: tools
  - save_cache:
      name: Save Yarn Tools Package Cache
      key: 2-yarn-{{ arch }}-{{ checksum "tools/yarn.lock" }}-{{ checksum "tools/package.json" }}
      paths:
        - tools/.yarn/cache
