jobs:
- check
- bump_version:
    delivery: development
- build_android:
    requires:
      - check
      - bump_version
- deliver_browser_stack:
    production_delivery: false
    requires:
      - build_android
- deliver_android:
    production_delivery: false
    requires:
      - build_android
