jobs:
  - bump_version:
      delivery: none
  - check
  - build_android:
      requires:
        - check
        - bump_version
  - deliver_browser_stack:
      production_delivery: false
      requires:
        - build_android