when: << pipeline.parameters.run_promote >>
jobs:
  - promote_android:
      context:
        - tuerantuer-google-play
  - promote_ios:
      context:
        - fastlane-match
        - tuerantuer-apple
