version: 2.1
jobs:
  check:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Linting check
          command: yarn lint
workflows:
  commit:
    jobs:
      - check