parameters:
  delivery:
    description: Which type of delivery is made. If none, the bumped version is not committed.
    type: enum
    enum: [none, development, production]
    default: none
docker:
  - image: circleci/node:12.16.3
resource_class: small
steps:
  - checkout
  - restore_yarn_tools_cache
  - run:
      name: Bump git version
      command: tools/git-version bump-to ${NEW_VERSION_NAME} ${NEW_VERSION_CODE} --deliverino-private-key ${DELIVERINO_PRIVATE_KEY} --owner ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --branch ${CIRCLE_BRANCH}
