docker:
  - image: circleci/node:12.16.3
resource_class: small
steps:
  - checkout
  - restore_yarn_tools_cache
  - run:
      name: Calculate next version name
      command: echo "export NEW_VERSION_NAME=$(tools/next-version calc | jq .versionName)" >> ${BASH_ENV}
  - run:
      name: Calculate next version code
      command: echo "export NEW_VERSION_CODE=$(tools/next-version calc | jq .versionCode)" >> ${BASH_ENV}
  - persist_environment_variables
