docker:
  - image: circleci/node:14.17.0
steps:
  - checkout
  - check_config
  - restore_yarn_cache
  - run:
      name: Linting check
      command: yarn lint
  - run:
      name: TS check
      command: yarn ts:check
  - run:
      name: Prettier check
      command: yarn prettier --check .
  - run:
      name: Run unit tests
      command: yarn test
