docker:
  - image: circleci/android:api-29-node
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
shell: /bin/bash -eo pipefail
steps:
  - add_ssh_keys: # Needed for credentials repo
      fingerprints:
        - 5b:28:97:36:8b:31:08:ae:5d:ad:19:8a:7d:6f:57:8a
  - checkout
  - prepare_workspace
  - restore_ruby_cache:
      directory: android
  - run:
      name: 'BrowserStack Upload android'
      command: bundle exec fastlane android upload_to_browserstack
      working_directory: android
  - restore_ruby_cache:
      directory: ios
  - run:
      name: 'BrowserStack Upload iOS'
      command: bundle exec fastlane ios upload_to_browserstack
      working_directory: ios
