parameters:
  production_delivery:
    description: Whether to deliver the build to production.
    type: boolean
docker:
  - image: circleci/android:api-29-node
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
shell: /bin/bash -eo pipefail
steps:
  - checkout
  - prepare_workspace
  - restore_environment_variables
  - restore_yarn_tools_cache
  - restore_ruby_cache:
      directory: android
  - run:
      name: Parse german android release notes
      command: tools/parse-release-notes parse --android --destination android/fastlane/metadata/de-DE/changelogs/default.txt --production
  - run:
      name: Validate Play Store Key
      command: bundle exec fastlane validate_play_store_key
      working_directory: android
  - prepare_workspace
  - restore_environment_variables
  - restore_yarn_cache
  #- run:
  #    name: PlayStore Upload
  #    command: bundle exec fastlane upload_to_playstore version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE} production_delivery:"<< parameters.production_delivery >>"
  #    working_directory: android
  - run:
      name: Sentry Upload
      command: tools/sentry-release.sh "app.lunes" "${NEW_VERSION_NAME}" ~/attached_workspace/sourcemaps/ --version-code "${NEW_VERSION_CODE}"
