# Promote the app from the beta to the production track in the Google Play Store.
docker:
  - image: circleci/android:api-29-node
resource_class: small
shell: /bin/bash -eo pipefail
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
steps:
  - checkout
  - restore_yarn_cache # Needed for babel-node run in read_build_config.rb. May be refactored and optimized later.
  - restore_ruby_cache:
      directory: android
  - run:
      name: '[FL] Play Store Promotion'
      command: bundle exec fastlane android playstore_promote
      working_directory: android
